
/*If there is a decreasing trend in winning bids, one might expect ISDs to use this fact. If you look at the order in which school districts
have their annual bid meetings, is there any change? Do we see ISDs holding their bid meetings later on and getting lower bids? */


/*This shows the number of times each district holds in let date in August*/
SELECT COUNTY, SYSTEM, COUNT(MONTH) as MONTHS,  SUM( CASE WHEN (MONTH>7) THEN 1 ELSE 0 END ) as LATE_BIDS
FROM milk
WHERE WIN  = 1
AND YEAR >= 1980
AND YEAR <= 1991
GROUP BY SYSTEM, COUNTY
ORDER BY COUNTY, SYSTEM


/*This shows the number of let dates by month a percentage*/
WITH SEASON AS (SELECT year, count(MONTH) as BIDS,
SUM(CASE WHEN ( MONTH = 5) THEN 1 ELSE 0 END) as MAY,
SUM(CASE WHEN ( MONTH = 6) THEN 1 ELSE 0 END) as JUNE,
SUM(CASE WHEN ( MONTH = 7) THEN 1 ELSE 0 END) as JULY,
SUM(CASE WHEN ( MONTH = 8) THEN 1 ELSE 0 END) as AUG
FROM milk
WHERE WIN  = 1
AND YEAR >= 1980 AND YEAR <= 1991
AND MONTH <> 0 AND DAY <> 0
GROUP BY YEAR
ORDER BY YEAR)

SELECT YEAR, ROUND(MAY/(BIDS*1.0),2) AS MAY,
ROUND(JUNE/(BIDS*1.0),2) AS JUNE,
ROUND(JULY/(BIDS*1.0),2) AS JULY,
ROUND(AUG/(BIDS*1.0),2) AS AUG
FROM SEASON


/*Shows which month the low bids occur in by percentage (low is <.15) */
WITH SEASON AS (SELECT year, count(MONTH) as BIDS,
SUM(CASE WHEN (WW<.15) THEN 1 ELSE 0 END) as LOW_BIDS,
SUM(CASE WHEN (WW<.15 and MONTH = 5) THEN 1 ELSE 0 END) as LOW_MAY,
SUM(CASE WHEN (WW<.15 and MONTH = 6) THEN 1 ELSE 0 END) as LOW_JUNE,
SUM(CASE WHEN (WW<.15 and MONTH = 7) THEN 1 ELSE 0 END) as LOW_JULY,
SUM(CASE WHEN (WW<.15 and MONTH = 8) THEN 1 ELSE 0 END) as LOW_AUG
FROM milk
WHERE WIN  = 1
AND YEAR >= 1980 AND YEAR <= 1991
AND MONTH <> 0 AND DAY <> 0
GROUP BY YEAR
ORDER BY YEAR)

SELECT YEAR, ROUND(LOW_MAY/(LOW_BIDS*1.0),2) AS PERCENT_MAY,
ROUND(LOW_JUNE/(LOW_BIDS*1.0),2) AS PERCENT_JUNE,
ROUND(LOW_JULY/(LOW_BIDS*1.0),2) AS PERCENT_JULY,
ROUND(LOW_AUG/(LOW_BIDS*1.0),2) AS PERCENT_AUG
FROM SEASON


/*this does both, and filters by city*/
WITH LOW AS (SELECT year, count(MONTH) as BIDS,
SUM(CASE WHEN (WW<.155) THEN 1 ELSE 0 END) as LOW_BIDS,
SUM(CASE WHEN (WW<.155 and MONTH = 5) THEN 1 ELSE 0 END) as MAY,
SUM(CASE WHEN (WW<.155 and MONTH = 6) THEN 1 ELSE 0 END) as JUNE,
SUM(CASE WHEN (WW<.155 and MONTH = 7) THEN 1 ELSE 0 END) as JULY,
SUM(CASE WHEN (WW<.155 and MONTH = 8) THEN 1 ELSE 0 END) as AUG
FROM milk
WHERE WIN  = 1
AND FMOZONE = 1
AND COUNTY <> 'WISE'
AND YEAR >= 1980 AND YEAR <= 1991
AND MONTH <> 0 AND DAY <> 0
GROUP BY YEAR
ORDER BY YEAR),

TOT AS (SELECT year, count(MONTH) as BIDS,
SUM(CASE WHEN ( MONTH = 5) THEN 1 ELSE 0 END) as MAY,
SUM(CASE WHEN ( MONTH = 6) THEN 1 ELSE 0 END) as JUNE,
SUM(CASE WHEN ( MONTH = 7) THEN 1 ELSE 0 END) as JULY,
SUM(CASE WHEN ( MONTH = 8) THEN 1 ELSE 0 END) as AUG
FROM milk
WHERE WIN  = 1
AND FMOZONE=1
AND COUNTY <> 'WISE'
AND YEAR >= 1980 AND YEAR <= 1991
AND MONTH <> 0 AND DAY <> 0
GROUP BY YEAR
ORDER BY YEAR)

SELECT TOT.YEAR AS YEAR, 
ROUND(TOT.MAY/(TOT.BIDS*1.0),2) AS MAY,
ROUND(LOW.MAY/(LOW.BIDS*1.0),2) AS LOW_MAY,
ROUND(TOT.JUNE/(TOT.BIDS*1.0),2) AS JUNE,
ROUND(LOW.JUNE/(TOT.BIDS*1.0),2) AS LOW_JUNE,
ROUND(TOT.JULY/(TOT.BIDS*1.0),2) AS JULY,
ROUND(LOW.JULY/(LOW.BIDS*1.0),2) AS LOW_JULY,
ROUND(TOT.AUG/(TOT.BIDS*1.0),2)  AS AUG,
ROUND(LOW.AUG/(LOW.BIDS*1.0),2) AS LOW_AUG
FROM TOT, LOW
WHERE TOT.YEAR = LOW.YEAR


/*Summarize the average quantities in each market*/
SELECT YEAR, FMOZONE, ROUND(avg(WW),4) as AVG_WW,
 ROUND(avg(ESTQTY),1) as AVG_QTY, COUNT(*) as OBS FROM milk
WHERE WIN  = 1
AND YEAR >= 1980 AND YEAR <= 1991
AND MONTH <> 0 AND DAY <> 0
AND WW<>'' and WW<>0
GROUP BY YEAR, FMOZONE
ORDER BY FMOZONE, YEAR